
exec-once = uwsm app -- systemctl --user restart kanshi
exec-once = uwsm app -- swaync
exec-once = uwsm app -- /home/gabwag/.config/waybar/waybar.sh
exec-once = uwsm app -- /usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
# exec-once = uwsm app -- clipse -listen
# exec-once = uwsm app -- safeeyes
# exec-once = uwsm app -- fcitx5 -d

# Idle configuration
exec-once = uwsm app -- hypridle

# open in specific workspaces
exec-once = [workspace 3 silent] uwsm app -- firefox -P "slack"
exec-once = [workspace 2 silent] uwsm app -- helium
#exec-once = [workspace special silent] uwsm app -- alacritty -e spotify_player
exec-once = [workspace 1 silent] uwsm app -- alacritty

