[colors.bright]
black = "#424242"
blue = "#8DA3B9"
cyan = "#8AA6A2"
green = "#8C977D"
magenta = "#A988B0"
red = "#B66467"
white = "#E8E3E3"
yellow = "#D9BC8C"

[colors.normal]
black = "#151515"
blue = "#8DA3B9"
cyan = "#8AA6A2"
green = "#8C977D"
magenta = "#A988B0"
red = "#B66467"
white = "#E8E3E3"
yellow = "#D9BC8C"

[colors.primary]
background = "#151515"
foreground = "#E8E3E3"

[cursor]
style = "beam"
thickness = 0.2
unfocused_hollow = false

[font]
size = 9

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0


[terminal.shell]
program = "/bin/zsh"

[window.padding]
x = 8
y = 8

[window]
opacity=0.9


